"""add user constraints

Revision ID: 44a4418b1794
Revises: 
Create Date: 2026-09-28 18:26:26.955587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a4418b1794'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.create_check_constraint('ck_users_role', 'users', "role IN ('admin', 'support', 'viewer')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_role', 'users', type_='check')
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    # ### end Alembic commands ###
