"""make target_user_id null on deletion

Revision ID: 81ff1c79c551
Revises: 5f644160634f
Create Date: 2026-10-05 17:40:26.522079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ff1c79c551'
down_revision: Union[str, Sequence[str], None] = '5f644160634f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'target_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('audit_logs_target_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_target_user_id_fkey', 'audit_logs', 'users', ['target_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_target_user_id_fkey'), 'audit_logs', 'users', ['target_user_id'], ['id'])
    op.alter_column('audit_logs', 'target_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
